class CountryData {
  final String name;
  final String dialCode;

  const CountryData({required this.name, required this.dialCode});
}

const List<CountryData> defaultCountries = [
  CountryData(name: 'Afghanistan', dialCode: '+93'),
  CountryData(name: 'Albania', dialCode: '+355'),
  CountryData(name: 'Algeria', dialCode: '+213'),
  CountryData(name: 'Andorra', dialCode: '+376'),
  CountryData(name: 'Angola', dialCode: '+244'),
  CountryData(name: 'Argentina', dialCode: '+54'),
  CountryData(name: 'Armenia', dialCode: '+374'),
  CountryData(name: 'Australia', dialCode: '+61'),
  CountryData(name: 'Austria', dialCode: '+43'),
  CountryData(name: 'Azerbaijan', dialCode: '+994'),
  CountryData(name: 'Bahamas', dialCode: '+1-242'),
  CountryData(name: 'Bahrain', dialCode: '+973'),
  CountryData(name: 'Bangladesh', dialCode: '+880'),
  CountryData(name: 'Barbados', dialCode: '+1-246'),
  CountryData(name: 'Belarus', dialCode: '+375'),
  CountryData(name: 'Belgium', dialCode: '+32'),
  CountryData(name: 'Belize', dialCode: '+501'),
  CountryData(name: 'Benin', dialCode: '+229'),
  CountryData(name: 'Bhutan', dialCode: '+975'),
  CountryData(name: 'Bolivia', dialCode: '+591'),
  CountryData(name: 'Bosnia and Herzegovina', dialCode: '+387'),
  CountryData(name: 'Botswana', dialCode: '+267'),
  CountryData(name: 'Brazil', dialCode: '+55'),
  CountryData(name: 'Brunei', dialCode: '+673'),
  CountryData(name: 'Bulgaria', dialCode: '+359'),
  CountryData(name: 'Burkina Faso', dialCode: '+226'),
  CountryData(name: 'Burundi', dialCode: '+257'),
  CountryData(name: 'Cambodia', dialCode: '+855'),
  CountryData(name: 'Cameroon', dialCode: '+237'),
  CountryData(name: 'Canada', dialCode: '+1'),
  CountryData(name: 'Cape Verde', dialCode: '+238'),
  CountryData(name: 'Central African Republic', dialCode: '+236'),
  CountryData(name: 'Chad', dialCode: '+235'),
  CountryData(name: 'Chile', dialCode: '+56'),
  CountryData(name: 'China', dialCode: '+86'),
  CountryData(name: 'Colombia', dialCode: '+57'),
  CountryData(name: 'Comoros', dialCode: '+269'),
  CountryData(name: 'Congo', dialCode: '+242'),
  CountryData(name: 'Congo (DRC)', dialCode: '+243'),
  CountryData(name: 'Costa Rica', dialCode: '+506'),
  CountryData(name: 'Croatia', dialCode: '+385'),
  CountryData(name: 'Cuba', dialCode: '+53'),
  CountryData(name: 'Cyprus', dialCode: '+357'),
  CountryData(name: 'Czech Republic', dialCode: '+420'),
  CountryData(name: 'Denmark', dialCode: '+45'),
  CountryData(name: 'Djibouti', dialCode: '+253'),
  CountryData(name: 'Dominica', dialCode: '+1-767'),
  CountryData(name: 'Dominican Republic', dialCode: '+1-809'),
  CountryData(name: 'Ecuador', dialCode: '+593'),
  CountryData(name: 'Egypt', dialCode: '+20'),
  CountryData(name: 'El Salvador', dialCode: '+503'),
  CountryData(name: 'Equatorial Guinea', dialCode: '+240'),
  CountryData(name: 'Eritrea', dialCode: '+291'),
  CountryData(name: 'Estonia', dialCode: '+372'),
  CountryData(name: 'Eswatini', dialCode: '+268'),
  CountryData(name: 'Ethiopia', dialCode: '+251'),
  CountryData(name: 'Fiji', dialCode: '+679'),
  CountryData(name: 'Finland', dialCode: '+358'),
  CountryData(name: 'France', dialCode: '+33'),
  CountryData(name: 'Gabon', dialCode: '+241'),
  CountryData(name: 'Gambia', dialCode: '+220'),
  CountryData(name: 'Georgia', dialCode: '+995'),
  CountryData(name: 'Germany', dialCode: '+49'),
  CountryData(name: 'Ghana', dialCode: '+233'),
  CountryData(name: 'Greece', dialCode: '+30'),
  CountryData(name: 'Grenada', dialCode: '+1-473'),
  CountryData(name: 'Guatemala', dialCode: '+502'),
  CountryData(name: 'Guinea', dialCode: '+224'),
  CountryData(name: 'Guinea-Bissau', dialCode: '+245'),
  CountryData(name: 'Guyana', dialCode: '+592'),
  CountryData(name: 'Haiti', dialCode: '+509'),
  CountryData(name: 'Honduras', dialCode: '+504'),
  CountryData(name: 'Hong Kong', dialCode: '+852'),
  CountryData(name: 'Hungary', dialCode: '+36'),
  CountryData(name: 'Iceland', dialCode: '+354'),
  CountryData(name: 'India', dialCode: '+91'),
  CountryData(name: 'Indonesia', dialCode: '+62'),
  CountryData(name: 'Iran', dialCode: '+98'),
  CountryData(name: 'Iraq', dialCode: '+964'),
  CountryData(name: 'Ireland', dialCode: '+353'),
  CountryData(name: 'Israel', dialCode: '+972'),
  CountryData(name: 'Italy', dialCode: '+39'),
  CountryData(name: 'Ivory Coast', dialCode: '+225'),
  CountryData(name: 'Jamaica', dialCode: '+1-876'),
  CountryData(name: 'Japan', dialCode: '+81'),
  CountryData(name: 'Jordan', dialCode: '+962'),
  CountryData(name: 'Kazakhstan', dialCode: '+7'),
  CountryData(name: 'Kenya', dialCode: '+254'),
  CountryData(name: 'Kiribati', dialCode: '+686'),
  CountryData(name: 'Kosovo', dialCode: '+383'),
  CountryData(name: 'Kuwait', dialCode: '+965'),
  CountryData(name: 'Kyrgyzstan', dialCode: '+996'),
  CountryData(name: 'Laos', dialCode: '+856'),
  CountryData(name: 'Latvia', dialCode: '+371'),
  CountryData(name: 'Lebanon', dialCode: '+961'),
  CountryData(name: 'Lesotho', dialCode: '+266'),
  CountryData(name: 'Liberia', dialCode: '+231'),
  CountryData(name: 'Libya', dialCode: '+218'),
  CountryData(name: 'Liechtenstein', dialCode: '+423'),
  CountryData(name: 'Lithuania', dialCode: '+370'),
  CountryData(name: 'Luxembourg', dialCode: '+352'),
  CountryData(name: 'Macau', dialCode: '+853'),
  CountryData(name: 'Madagascar', dialCode: '+261'),
  CountryData(name: 'Malawi', dialCode: '+265'),
  CountryData(name: 'Malaysia', dialCode: '+60'),
  CountryData(name: 'Maldives', dialCode: '+960'),
  CountryData(name: 'Mali', dialCode: '+223'),
  CountryData(name: 'Malta', dialCode: '+356'),
  CountryData(name: 'Marshall Islands', dialCode: '+692'),
  CountryData(name: 'Mauritania', dialCode: '+222'),
  CountryData(name: 'Mauritius', dialCode: '+230'),
  CountryData(name: 'Mexico', dialCode: '+52'),
  CountryData(name: 'Micronesia', dialCode: '+691'),
  CountryData(name: 'Moldova', dialCode: '+373'),
  CountryData(name: 'Monaco', dialCode: '+377'),
  CountryData(name: 'Mongolia', dialCode: '+976'),
  CountryData(name: 'Montenegro', dialCode: '+382'),
  CountryData(name: 'Morocco', dialCode: '+212'),
  CountryData(name: 'Mozambique', dialCode: '+258'),
  CountryData(name: 'Myanmar', dialCode: '+95'),
  CountryData(name: 'Namibia', dialCode: '+264'),
  CountryData(name: 'Nauru', dialCode: '+674'),
  CountryData(name: 'Nepal', dialCode: '+977'),
  CountryData(name: 'Netherlands', dialCode: '+31'),
  CountryData(name: 'New Zealand', dialCode: '+64'),
  CountryData(name: 'Nicaragua', dialCode: '+505'),
  CountryData(name: 'Niger', dialCode: '+227'),
  CountryData(name: 'Nigeria', dialCode: '+234'),
  CountryData(name: 'North Korea', dialCode: '+850'),
  CountryData(name: 'North Macedonia', dialCode: '+389'),
  CountryData(name: 'Norway', dialCode: '+47'),
  CountryData(name: 'Oman', dialCode: '+968'),
  CountryData(name: 'Pakistan', dialCode: '+92'),
  CountryData(name: 'Palau', dialCode: '+680'),
  CountryData(name: 'Palestine', dialCode: '+970'),
  CountryData(name: 'Panama', dialCode: '+507'),
  CountryData(name: 'Papua New Guinea', dialCode: '+675'),
  CountryData(name: 'Paraguay', dialCode: '+595'),
  CountryData(name: 'Peru', dialCode: '+51'),
  CountryData(name: 'Philippines', dialCode: '+63'),
  CountryData(name: 'Poland', dialCode: '+48'),
  CountryData(name: 'Portugal', dialCode: '+351'),
  CountryData(name: 'Puerto Rico', dialCode: '+1-787'),
  CountryData(name: 'Qatar', dialCode: '+974'),
  CountryData(name: 'Romania', dialCode: '+40'),
  CountryData(name: 'Russia', dialCode: '+7'),
  CountryData(name: 'Rwanda', dialCode: '+250'),
  CountryData(name: 'Saint Kitts and Nevis', dialCode: '+1-869'),
  CountryData(name: 'Saint Lucia', dialCode: '+1-758'),
  CountryData(name: 'Saint Vincent and the Grenadines', dialCode: '+1-784'),
  CountryData(name: 'Samoa', dialCode: '+685'),
  CountryData(name: 'San Marino', dialCode: '+378'),
  CountryData(name: 'Sao Tome and Principe', dialCode: '+239'),
  CountryData(name: 'Saudi Arabia', dialCode: '+966'),
  CountryData(name: 'Senegal', dialCode: '+221'),
  CountryData(name: 'Serbia', dialCode: '+381'),
  CountryData(name: 'Seychelles', dialCode: '+248'),
  CountryData(name: 'Sierra Leone', dialCode: '+232'),
  CountryData(name: 'Singapore', dialCode: '+65'),
  CountryData(name: 'Slovakia', dialCode: '+421'),
  CountryData(name: 'Slovenia', dialCode: '+386'),
  CountryData(name: 'Solomon Islands', dialCode: '+677'),
  CountryData(name: 'Somalia', dialCode: '+252'),
  CountryData(name: 'South Africa', dialCode: '+27'),
  CountryData(name: 'South Korea', dialCode: '+82'),
  CountryData(name: 'South Sudan', dialCode: '+211'),
  CountryData(name: 'Spain', dialCode: '+34'),
  CountryData(name: 'Sri Lanka', dialCode: '+94'),
  CountryData(name: 'Sudan', dialCode: '+249'),
  CountryData(name: 'Suriname', dialCode: '+597'),
  CountryData(name: 'Sweden', dialCode: '+46'),
  CountryData(name: 'Switzerland', dialCode: '+41'),
  CountryData(name: 'Syria', dialCode: '+963'),
  CountryData(name: 'Taiwan', dialCode: '+886'),
  CountryData(name: 'Tajikistan', dialCode: '+992'),
  CountryData(name: 'Tanzania', dialCode: '+255'),
  CountryData(name: 'Thailand', dialCode: '+66'),
  CountryData(name: 'Timor-Leste', dialCode: '+670'),
  CountryData(name: 'Togo', dialCode: '+228'),
  CountryData(name: 'Tonga', dialCode: '+676'),
  CountryData(name: 'Trinidad and Tobago', dialCode: '+1-868'),
  CountryData(name: 'Tunisia', dialCode: '+216'),
  CountryData(name: 'Turkey', dialCode: '+90'),
  CountryData(name: 'Turkmenistan', dialCode: '+993'),
  CountryData(name: 'Tuvalu', dialCode: '+688'),
  CountryData(name: 'Uganda', dialCode: '+256'),
  CountryData(name: 'Ukraine', dialCode: '+380'),
  CountryData(name: 'United Arab Emirates', dialCode: '+971'),
  CountryData(name: 'United Kingdom', dialCode: '+44'),
  CountryData(name: 'United States', dialCode: '+1'),
  CountryData(name: 'Uruguay', dialCode: '+598'),
  CountryData(name: 'Uzbekistan', dialCode: '+998'),
  CountryData(name: 'Vanuatu', dialCode: '+678'),
  CountryData(name: 'Vatican City', dialCode: '+39'),
  CountryData(name: 'Venezuela', dialCode: '+58'),
  CountryData(name: 'Vietnam', dialCode: '+84'),
  CountryData(name: 'Yemen', dialCode: '+967'),
  CountryData(name: 'Zambia', dialCode: '+260'),
  CountryData(name: 'Zimbabwe', dialCode: '+263'),
];
